//  {"easy":["title",["clue","clue","clue","clue"]],"medium":["title",["clue","clue","clue","clue"]],"harder":["title",["clue","clue","clue","clue"]],"difficult":["title",["clue","clue","clue","clue"]]},
//{"easy":[],"medium":[],"harder":[],"difficult":[]},

    let json = [
        {"easy":["FAMILIA FEMENINA",["TIA","ABUELA","HERMANA","MADRE"]],"medium":["FAMILIA MASCULINA",["TIO","ABUELO","HEMARNO","PADRE"]],"harder":["AMIGO MASCULINA",["AMIGO","COMPAÑERO","AMIGOTE","CHICO"]],"difficult":["AMIGA FEMENINA",["AMIGA","COMPAÑERA","AMIGOTA","CHICA"]]},
        {"easy":["PRONOMBRES",["YO","TÚ","ÉL","ELLA"]],"medium":["VERBO SER",["SOY","ERES","ES","SOMOS"]],"harder":["VERBO VER",["VEO","VES","VE","VEMOS"]],"difficult":["VERBO IR",["VOY","VAS","VAMOS","VA"]]},
        {"easy":["TIENES PELO",["CORTO","MEDIA MELENA","LARGO","RECOGIDO"]],"medium":["TU ES",["JOVEN","VIEJO","NENE","MAYOR"]],"harder":["PARACES",["FELIZ","TRISTE","ALEGRE","TIMIDO"]],"difficult":["EN TU CABEZA",["GORRA","GORRO","CASCO","SOMBRERO"]]},
        {"easy":["LAS PREPOSICIONES DE LUGAR",["AL LA IZQUIERDA","A LA DERECHA","DELANTE","DETRÁS"]],"medium":["ANTES DEL SUSTANTIO",["MI","TU","SU","SUS"]],"harder":["DESPUÉ DEL SUSTANTIVO",["MIO","TUYO","SUYO","SUYOS"]],"difficult":["VERBO HACER",["HAGO","HACES","HACE","HACEN"]]},
        {"easy":["DÍAS DE LA SEMANA",["DOMINGO","LUNES","SÁBADO","JUEVES"]],"medium":["ALIMENTOS",["HUEVOS","QUESO","POLLO","CAMARÓN"]],"harder":["ENCONTRADO EN ASTRONOMÍA",["LUNA","SOL","ESTRELLA","COMETA"]],"difficult":["NÚMEROS",["DOS","SIETE","DIEZ","VEINTE"]]},
        {"easy":["TERRENO",["SIERRA","VALLE","RIO","PAMPA"]],"medium":["ACCIONES DE VENTANA",["CIERRA","ABRE","CUBRE","LAVA"]],"harder":["UNIDADES DE TIEMPO",["HORA","MES","QUINCENA","AÑO"]],"difficult":["UN ANHELO POR",["ORAR","DESEAR","ESPERAR","DESEO"]]},
        {"easy":["VERDURAS",["TOMATE","GUISANTES","PIMENTO","PAPAS"]],"medium":["INGREDIENTES DE LA PAELLA",["CEBOLLA","CHORIZOS","ARROZ","POLLO"]],"harder":["PARA EL DESAYUNO",["JUGO","HUEVOS","FRUTA","PAN"]],"difficult":["MESES",["ENERO","MARZO","MAYO","JUNIO"]]},
        {"easy":["EL TAMAÑO IMPORTA",["ALTO","GRANDE","CHICO","PEQUEÑO"]],"medium":["CARACTERÍSTICAS DEL MAPA",["ALDEA","CALLE","AVENDA","CUIDAD"]],"harder":["EXCLAMACIONES E INTERJECCIONES",["OYE","PERO","TAMBIÉN","VALE"]],"difficult":["A LO LARGO DE LA AVENIDA",["RESTAURANTE","TIENDA","TEATRO","MUSEO"]]},
        {"easy":["CANDIDAD",["MUCHO","PEQUEÑO","TODO","TANTO"]],"medium":["FIESTA",["MÚSICA","PIÑATA","TORTA","RESFRESCOS"]],"harder":["INTERROGATIVAS",["CÓMO","CUÁNDO","DÓNDE","POR QUÉ"]],"difficult":["COMUNIDAD AUTÓNOMA",["ANDALUSIA","ASTURIAS","CANTABRIA","GALICIA"]]},
        {"easy":["SALUDOS",["¡HOLA!","¿QUÉ TAL?","BIENVENIDA","¿CóMO ESTÁS?"]],"medium":["¿QUÉ HORA ES?",["MEDIODÍA","MEDIA HORA","MEDIANOCHE","TRES Y MEDIA"]],"harder":["TEMPORADA",["PRIMAVERA","VERANO","OTOÑO","INVIERNO"]],"difficult":["HORTICULTURA",["FLOR","ÁRBOL","JARDÍN","HOJAS"]]},
        {"easy":["VERBOS IRREGULAR - VOLVER",["VOLVER","VUELO","VUELVE","VOLVÉIS"]],"medium":["VERBOS IRREGULAR - TRAER",["TRAER","TRAIGO","TRAE","TRAÉIS"]],"harder":["VERBOS IRREGULAR - SOÑAR",["SOÑAR","SUEÑO","SUEÑA","SOÑAIS"]],"difficult":["VERBOS IRREGULAR - QUERER",["QUERER","QUIERO","QUIERE","QUERÉIS"]]},
        {"easy":["QUÁNDO",["HOY","AYER","PRONTO","MAÑANA"]],"medium":["DIRECCIONES",["LEJOS","ALLI","ENTRE","JUNTO"]],"harder":["EL CLIMA",["VENTOSO","LLUEVE","NUBLADO","FRESCO"]],"difficult":["BUSCANDO CASA",["VENTA","AQUILAR","PRÉSTAMO","COMPRA"]]},
        {"easy":["LA ROPA",["CAMISA","PANTALONES","MEDIAS","FALADA"]],"medium":["COLOR DE PELO",["CALVO","RUBIO","MORENO","PELIRROJO"]],"harder":["JOYAS",["PENDIENTES","PULSERA","COLLAR","RELOJ"]],"difficult":["EN TUS PIES",["ZAPATOS","SANDALIAS","BOTAS","CALCETINES"]]},
        {"easy":["COMER CON",["TAZA","TENEDOR","VASO","CUCHILLO"]],"medium":["LAS LEGUMBREA",["CEBOLLA","PAPA","ESPINACA","ZANAHORIA"]],"harder":["LAS FRUTAS",["MANZANA","UVAS","NARANJA","FRESA"]],"difficult":["LAS BEBIDAS",["CERVESA","VINO","REFRESCO","CAFÉ"]]},
        {"easy":["DEPORTES",["CICLISMO","ESQUI","NATACIÓ","BALONCESTO"]],"medium":["HABITANTES",["ALEMÁN","CHILENO","CHINO","SUIZO"]],"harder":["LAS PROFESIONES EN LA COCINA",["PESCADERO","COCINERO","CARCINERO","PASTELERO"]],"difficult":["A TU SALUD",["DENTISTA","ENFERMERA","DOCTURA","FARMACEUTICA"]]},
        {"easy":["¿ALGO PARA BEBER?",["CERVESA","CAÑA","VINO","CALIMOCHO"]],"medium":["PROTEÍNA PARA LA CENA",["BACALAO","SOLOMILLO","LOMO","JAMÓN"]],"harder":["SALCHICHA CURADA",["MORCILLA","CHORIZO","SALCHICHON","BOTIFARRA"]],"difficult":["TAPAS",["MIGAS","TORTILLA","CROQUETAS","PATATAS BRAVAS"]]},    
        {"easy":["LOS OJOS",["AZULES","GRISES","VERDES","MARRONES"]],"medium":["ANIMALES",["PERRO","CABALLO","ÁGUILA","MONO"]],"harder":["SALUDOS",["CABALLERO","MAESTRA","HIDALGO","DON"]],"difficult":["COSAS QUE SON AZULES",["MAR","CIELO","OJOS","ARÁNDANOS"]]},
        {"easy":["ESTOY ALGO PERDIDA",["COMO LLEGO A","DONDE ESTA","DONDE HAY","DONDE QUERA"]],"medium":["¿ADÓNDE?",["AQUÍ","AHÍ","ALLÁ","ACÁ"]],"harder":["NO DAR VUELTA",["DERECHO","CONTINUAR","MISMA DIRECCION","AL FRENTE"]],"difficult":["VIAJE DEL PUNTO A AL PUNTO B",["ITINERARIO","DESTINO","RUTA","RUMBO"]]},
        {"easy":["TODO LO QUE HACES ES TOMAR",["LLEVAR","TOMAR","SACAR","COGER"]],"medium":["TENGO HAMBRE",["COMIÓ","COMIDO","COMER","COMIENDO"]],"harder":["SER O...",["ESTAR","HACER","SER","TENER"]],"difficult":["HABLEMOS DE ELLO",["HABLAR","CONVERSAR","DECIR","CHARLAR"]]}
    ];